enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

##########
# dont build on gh actions (https://github.com/j-hc/revanced-magisk-module/issues/554)

#https://j-hc.github.io/rvmm-config-gen/
####################################################################################################
#inotia00-5.6.2
[YTMusic]
app-name = "YouTube Music"
arch = "arm64-v8a"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "inotia00 ReVanced"
included-patches = "'Hide overlay filter' 'Hide player overlay filter' 'Disable music video in album' 'Return YouTube Username'"
excluded-patches = "'Custom branding icon for YouTube Music' 'Custom branding name for YouTube Music'"

[Reddit]
app-name = "Reddit"
arch = "arm64-v8a"
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "inotia00 ReVanced"

[YouTube]
app-name = "YouTube"
arch = "arm64-v8a"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "inotia00 ReVanced"
included-patches = "'Hide Shorts dimming' 'Force hide player buttons background' 'Hide shortcuts' 'MaterialYou' 'Return YouTube Username'"
excluded-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube'"
####################################################################################################
#revanced-5.18.0.json
[Instagram]
arch = "arm64-v8a"
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.instagram.android"

[Messenger]
arch = "arm64-v8a"
apkmirror-dlurl = "https://apkmirror.com/apk/facebook-2/messenger/"
uptodown-dlurl = "https://facebook-messenger.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.facebook.orca"

[Tiktok]
arch = "arm64-v8a"
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
uptodown-dlurl = "https://tiktok.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.zhiliaoapp.musically"
included-patches = "'SIM spoof'"

[Backdrops]
app-name = "Backdrops"
arch = "arm64-v8a"
apkmirror-dlurl = "https://apkmirror.com/apk/backdrops/backdrops-wallpapers/"

[GooglePhotos]
app-name = "GooglePhotos"
arch = "arm64-v8a"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"

[Spotify]
app-name = "Spotify"
arch = "arm64-v8a"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
included-patches = "'Custom theme'"

[Yuka]
app-name = "Yuka"
arch = "arm64-v8a"
apkmirror-dlurl = "https://apkmirror.com/apk/yuka-apps/yuka-food-cosmetic-scan/"
####################################################################################################

[Music-Extended]
enabled = false
app-name = "Music"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "both"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[YouTube-Extended]
enabled = false
app-name = "YouTube"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

###
[Music]
enabled = false
arch = "arm64-v8a"
included-patches = "'Disable music video in album' 'Hide overlay filter' 'Hide player overlay filter'"
excluded-patches = "'Custom branding icon for YouTube Music' 'Custom branding name for YouTube Music'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
